#!/bin/bash
#Mappa generale:
#Per me andrebbe fatto uno standard per capire come/dove gestire/mettere gli/i scripts/files 
#Struttura del preinst: step 1: modifica pacchetti. step 2: modifica configurazioni.
# non credo convenga creare tanti scripts eseguiti da questo, anche perché non so se dpkg li gestisce... Per ora stendo uno scriptino pattonissimo, poi ne riparliamo
echo "running step 1"
#Remove Packages - in ordine, programmi, guide, fonts e pacchetti lingua
apt-cache search language-pack | grep -v Italian |sed 's/\ -\ .*//g' |xargs dpkg --remove 
#openoffice.org-help-en* --> lo rimuoviamo come abbiamo fatto per i pacchetti lingua generici insieme a quelli delle altre lingue 
apt-get purge -y evolution-exchange gnome-games* gbrainy example-content empathy empathy-common gwibber rhythmbox tomboy yelp gnome-user-guide ubuntu-docs ttf-takao-pgothic ttf-symbol-replacement ttf-thai-tlwg ttf-khmeros-core ttf-lao ttf-kacst-one ttf-wqy-microhei
apt-get install -y localepurge vlc thunderbird emesene gimp evilwm mplayer htop sl cheese deborphan grub nautilus-actions wicd-curses
sudo apt-get -y autoremove
update-grub #serve?
# Hacks and Tricks
#swap trick
sysctl -q vm.swappiness
sysctl vm.swappiness=10
#TTY removal
echo "
VERBOSE_OUTPUT=no
ACTIVE_CONSOLES="/dev/tty[1-2]"
CHARMAP="UTF-8"
CODESET="Lat15"
FONTFACE="VGA"
FONTSIZE="16"
XKBMODEL="pc105"
XKBLAYOUT="it"
XKBVARIANT=""
XKBOPTIONS=""
"> /etc/default/console-setup
echo "
respawn
exec /sbin/getty -8 38400 tty3
" > /etc/init/tty3.conf
echo "
respawn
exec /sbin/getty -8 38400 tty4
" > /etc/init/tty4.conf
echo "
respawn
exec /sbin/getty -8 38400 tty5
" > /etc/init/tty5.conf
echo "
respawn
exec /sbin/getty -8 38400 tty6
" > /etc/init/tty6.conf
# Disattivazione di alcuni repo ufficiali (i repo ppa verranno installati direttamente col deb)
#creo il backup prima
cp /etc/apt/sources.list /etc/apt/sources.list.ubuntu.backup
#commento i repo e decommento multiverse e universe 
cat /etc/apt/sources.list |sed 's/deb\ http://archive.ubuntu.com/ubuntu\ lucid\ main restricted/#deb\ http://archive.ubuntu.com/ubuntu\ lucid\ main\ restricted/g' |sed 's/deb\ http://security.ubuntu.com/ubuntu\ lucid-security\ main\ restricted/#deb\ http://security.ubuntu.com/ubuntu\ lucid-security\ main\ restricted/g' |sed 's/deb\ http://archive.ubuntu.com/ubuntu\ lucid-updates\ main\ restricted/#deb\ http://archive.ubuntu.com/ubuntu\ lucid-updates\ main\ restricted/g' |sed 's/#\ deb http://archive.ubuntu.com/ubuntu\ lucid\ universe/deb\ http://archive.ubuntu.com/ubuntu\ lucid universe/g' |sed 's/#\ deb\ http://archive.ubuntu.com/ubuntu\ lucid\ multiverse/deb\ http://archive.ubuntu.com/ubuntu\ lucid\ multiverse/g'> /tmp/sources.list.tmp
mv /tmp/sources.list.tmp /etc/apt/sources.list
#cambio nome distro
cp /etc/lsb-release /etc/lsb-release.ubuntu
cat /etc/lsb-release |sed 's/[u-U]buntu/Anguix/g' |sed 's/lucid/Viridis/g' |sed 's/10.04.1 LTS/0.1alpha5/g' | sed 's/10.04/0.1alpha5/g' > /tmp/lsb-release.tmp
mv /tmp/lsb-release.tmp /etc/lsb-release





# Nel postinst inseriremo anche le chiamata gconf da aggiungere di default, per esempio per mettere i pannelli trasparenti di default, aggiungere dockbarx di default, etc. etc.
#Nel postinst verrà anche messa l'esecuzione di nautilus-scripts-installer, che aggiunge gli scripts by xela92 in nautilus-actions (i files per fare ciò sono nella dir /usr/share/nautilus-scripts-installer, che verrà installata tramite deb)


