[Desktop Entry]
Name=Murrina-Mint-4-Anguix
Type=X-GNOME-Metatheme
Comment=

[X-GNOME-Metatheme]
GtkTheme=Murrina-Mint-4-Anguix
MetacityTheme=InHuman
IconTheme=Humanity-Dark
GtkColorScheme=fg_color:#ffffff,bg_color:#181818,base_color:#353535,text_color:#ffffff,selected_bg_color:#11A819,selected_fg_color:#ffffff,tooltip_bg_color:#9D9D9D,tooltip_fg_color:#000000
CursorTheme=DMZ-Black
CursorSize=24
NotificationTheme=ubuntu
BackgroundImage=/usr/share/backgrounds/moreliaviridis2.png
